import Head from 'next/head';
import { CommonLayout } from '@/components/layout/common-layout';
import { ReactElement, ReactNode } from 'react';
import { useTagArtworksQuery } from '@/graphql/__generated__/graphql';
import GridArtworks from '@/components/common/grid-artworks';
import TagName from '@/components/tag/tag-name';
import { useRouter } from 'next/router';
import { MainLayout } from '@/components/layout/main-layout';
import MainContainer from '@/components/common/main-container';

export default function Tag() {
    const router = useRouter();
    const { tag } = router.query;
    const { data, loading, error, fetchMore, refetch } = useTagArtworksQuery({
        variables: {
            tagname: tag as string,
        },
        notifyOnNetworkStatusChange: true,
        // fetchPolicy: 'network-only',
        nextFetchPolicy: 'cache-first',
    });

    return (
        <>
            <Head>
                <title>{tag}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainContainer>
                <TagName tagname={tag as string} />
                {!data && loading && <div>TAG ARTWORKS LOADING</div>}

                <button
                    className="self-end font-bold text-black bg-pink-300 px-2 py-1 mb-2 rounded-md"
                    onClick={() => refetch()}
                >
                    Check For New Posts
                </button>

                {data?.tagArtworks.artworks && !error && (
                    <>
                        <GridArtworks artworks={data.tagArtworks.artworks} />
                    </>
                )}
                {/* Eventually will be moved into an infinite scroll component */}
                {data && data?.tagArtworks.hasMore && (
                    <button
                        className="w-26 mx-auto font-bold text-black bg-pink-300 px-2 py-1 mb-2 rounded-md"
                        onClick={() => {
                            fetchMore({
                                variables: {
                                    take: 10,
                                    skip: data.tagArtworks.artworks.length,
                                },
                            });
                        }}
                    >
                        Load More Artworks
                    </button>
                )}
            </MainContainer>
        </>
    );
}

Tag.getLayout = (page: ReactElement): ReactNode => (
    <CommonLayout>
        <MainLayout>{page}</MainLayout>
    </CommonLayout>
);
