import Head from 'next/head';
import { CommonLayout } from '@/components/layout/common-layout';
import { ReactElement, ReactNode } from 'react';
import UserContainer from '@/components/user/user-container';
import UserDetails from '@/components/user/user-details';
import UserArtworks from '@/components/user/user-artworks';
import { useRouter } from 'next/router';
import { useUserQuery } from '@/graphql/__generated__/graphql';

export default function User() {
    const router = useRouter();
    const { user } = router.query;
    const { data, loading, error } = useUserQuery({ variables: { username: user as string } });

    return (
        <>
            <Head>
                <title>{user}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <UserContainer>
                {!data && loading && <div>USER LOADING</div>}
                {data?.user.user && !error && (
                    <>
                        <UserDetails
                            username={data.user.user.username}
                            avatarUrl={data.user.user.avatarUrl}
                            isFollowedByLoggedInUser={data?.user.user.isFollowedByLoggedInUser ?? false}
                        />
                        <UserArtworks artworks={data.user.user.artworks} />
                    </>
                )}
            </UserContainer>
        </>
    );
}

User.getLayout = (page: ReactElement): ReactNode => <CommonLayout>{page}</CommonLayout>;
