import Head from 'next/head';
import { CommonLayout } from '@/components/layout/common-layout';
import { ReactElement, ReactNode } from 'react';
import ExploreContainer from '@/components/explore/explore-container';
import { useUserExploreTagsQuery, useUserExploreQuery } from '@/graphql/__generated__/graphql';
import GridArtworks from '@/components/common/grid-artworks';
import Tag from '@/components/common/tag';

export default function Explore() {
    const {
        data: tags_data,
        loading: tags_loading,
        error: tags_error,
    } = useUserExploreTagsQuery({ fetchPolicy: 'network-only', nextFetchPolicy: 'cache-first' });

    const {
        data: artworks_data,
        loading: artworks_loading,
        error: artworks_error,
        fetchMore,
    } = useUserExploreQuery({
        notifyOnNetworkStatusChange: true,
        fetchPolicy: 'network-only',
        nextFetchPolicy: 'cache-first',
    });

    return (
        <>
            <Head>
                <title>Explore</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ExploreContainer>
                {!artworks_data && artworks_loading && <div>EXPLORE ARTWORKS LOADING</div>}
                {!tags_data && tags_loading && <div>EXPLORE TAGS LOADING</div>}
                {tags_data?.userExploreTags.tags && !tags_error && (
                    <div className="flex gap-1">
                        {tags_data?.userExploreTags.tags.map((tag) => (
                            <Tag key={tag.tagname} id={tag.id} tagname={tag.tagname} />
                        ))}
                    </div>
                )}
                {artworks_data?.userExplore.artworks && !artworks_error && (
                    <>
                        <GridArtworks artworks={artworks_data.userExplore.artworks} />
                    </>
                )}
                {/* Eventually will be moved into an infinite scroll component */}
                {artworks_data && artworks_data?.userExplore.hasMore && (
                    <button
                        className="w-26 mx-auto text-pink-500 bg-black px-2 py-1 rounded-md"
                        onClick={() => {
                            fetchMore({
                                variables: {
                                    limit: 10,
                                    cursor: parseInt(
                                        artworks_data.userExplore.artworks[
                                            artworks_data.userExplore.artworks.length - 1
                                        ].id
                                    ),
                                },
                            });
                        }}
                    >
                        Load More Posts
                    </button>
                )}
            </ExploreContainer>
        </>
    );
}

Explore.getLayout = (page: ReactElement): ReactNode => <CommonLayout>{page}</CommonLayout>;
