import Head from 'next/head';
import { useUserFeedQuery } from '@/graphql/__generated__/graphql';
import { CommonLayout } from '@/components/layout/common-layout';
import { HomeLayout } from '@/components/layout/home-layout';
import { ReactElement, ReactNode } from 'react';
import HomeMainFeedContainer from '@/components/home/home-main-feed-container';
import { toast } from 'react-hot-toast';
import ArtworkContainer from '@/components/artwork/artwork-container';

const jojojacky = 'JoJoJacKy';
const password = 'qwerty';

export default function Home() {
    const { data, loading, error } = useUserFeedQuery();
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeMainFeedContainer>
                {!data && loading && <div>ARTWORKS LOADING</div>}
                {data?.userFeed.artworks &&
                    !error &&
                    data?.userFeed.artworks.map((artwork) => (
                        <ArtworkContainer
                            title={artwork.title}
                            id={artwork.id}
                            imageUrls={artwork.imageUrls}
                            description={artwork.description}
                            likesCount={artwork.likesCount}
                            createdAt={artwork.createdAt}
                            uploader={artwork.uploader}
                            topComment={artwork.topComment!}
                        />
                    ))}
            </HomeMainFeedContainer>
        </>
    );
}

Home.getLayout = (page: ReactElement): ReactNode => (
    <CommonLayout>
        <HomeLayout>{page}</HomeLayout>
    </CommonLayout>
);
