import Head from 'next/head';
import { useHelloQuery, useUserLoginMutation, useArtworkQuery } from '@/graphql/__generated__/graphql';
import { CommonLayout } from '@/components/layout/common-layout';
import { HomeLayout } from '@/components/layout/home-layout';
import { ReactElement, ReactNode } from 'react';
import HomeMainFeedContainer from '@/components/home/home-main-feed-container';
import { toast } from 'react-hot-toast';

const jojojacky = 'JoJoJacKy';
const password = 'qwerty';

export default function Home() {
    const { data: hello_data, error, loading } = useHelloQuery();
    const {
        data: artwork_data,
        error: artwork_error,
        loading: artwork_loading,
    } = useArtworkQuery({
        variables: {
            artworkId: '1',
        },
    });
    const [userLogin, { data: user_data }] = useUserLoginMutation();

    const handleLogin = async () => {
        const response = await userLogin({
            variables: {
                username: jojojacky,
                password: password,
            },
        });

        console.log(response);
        toast('User Logged In!');
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeMainFeedContainer>
                <div className="text-3xl font-bold">Shalom World</div>
                <button onClick={handleLogin}>LOGIN</button>
                {hello_data && <div className="text-6xl">{hello_data.hello}</div>}
                {user_data && (
                    <div>
                        <p>{user_data.userLogin.user?.username}</p>
                        <p>{user_data.userLogin.user?.email}</p>
                        <img src={user_data.userLogin.user?.avatarUrl ?? ''} alt="" />
                    </div>
                )}
                {!artwork_data && artwork_loading && <div>ARTWORK LOADING</div>}
                {artwork_data && (
                    <div className="flex flex-col">
                        <p>{artwork_data.artwork.artwork?.uploader.username}</p>
                        <p>{artwork_data.artwork.artwork?.title}</p>
                        {artwork_data.artwork.artwork?.imageUrls.map((url) => (
                            <img src={url}></img>
                        ))}
                        {artwork_data.artwork.artwork?.imageUrls.map((url) => (
                            <img src={url}></img>
                        ))}
                        {artwork_data.artwork.artwork?.imageUrls.map((url) => (
                            <img src={url}></img>
                        ))}
                        <p>{artwork_data.artwork.artwork?.description}</p>
                        {artwork_data.artwork.artwork?.isLikedByLoggedInUser ? (
                            <p>LIKED BY USER</p>
                        ) : (
                            <p>NOT LIKED BY USER</p>
                        )}
                    </div>
                )}
            </HomeMainFeedContainer>
        </>
    );
}

Home.getLayout = (page: ReactElement): ReactNode => (
    <CommonLayout>
        <HomeLayout>{page}</HomeLayout>
    </CommonLayout>
);
