import Head from 'next/head';
import Link from 'next/link';

export default function Landing() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-3xl font-bold">Landing Page</div>
            <Link href={'/home'}>Home</Link>
        </>
    );
}
