import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useHelloQuery } from '@/graphql/__generated__/graphql';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const { data, error, loading } = useHelloQuery();
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="text-3xl font-bold">Shalom World</div>
			{data && <div className="text-6xl">{data.hello}</div>}
		</>
	);
}
