import Head from 'next/head';
import { Toaster } from 'react-hot-toast';
import useUser from '@/lib/hooks/useUser';
import LoginForm from '@/components/login/login-form';

export default function Login() {
    const user = useUser();

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col w-screen h-screen justify-center items-center">
                <LoginForm />
            </div>
            <Toaster />
        </>
    );
}
