import Head from 'next/head';
import { Toaster } from 'react-hot-toast';
import useUser from '@/lib/hooks/useUser';
import RegisterForm from '@/components/register/register-form';

export default function Register() {
    const user = useUser();

    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col w-screen h-screen justify-center items-center">
                <RegisterForm />
            </div>
            <Toaster />
        </>
    );
}
