import Head from 'next/head';
import Link from 'next/link';
import { Tab } from '@headlessui/react';

export default function TheLab() {
    const categories = ['Artworks', 'Likes'];
    function classNames(...classes: any) {
        return classes.filter(Boolean).join(' ');
    }

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="w-screen h-screen">
                <p>Blog</p>
                <Link href={'/'}>HOME</Link>

                <Tab.Group>
                    <Tab.List className="flex p-1 gap-10 w-full justify-center">
                        {categories.map((category) => (
                            <Tab
                                key={category}
                                className={({ selected }) =>
                                    classNames(
                                        'w-16 font-bold text-black border-b-2 focus:outline-none',
                                        selected ? ' text-[#DE5D82] border-b-2 border-[#DE5D82]' : ''
                                    )
                                }
                            >
                                {category}
                            </Tab>
                        ))}
                    </Tab.List>
                    <Tab.Panels>
                        <Tab.Panel>Content 1</Tab.Panel>
                        <Tab.Panel>Content 2</Tab.Panel>
                    </Tab.Panels>
                </Tab.Group>
            </div>
        </>
    );
}
